### ISSUE TITLE
cannot load trip after creation

### ISSUE THREAD

**Issue by Nin3s** [ucf-senior-design/senior-design#240] opened 2023-04-11 14:43 UTC
after creating a trip, page loads for a long time and an error “cannot load trip” is shown, the trip card is created however

refreshing the page redirects the user to log in again and the same problem occurs

**Comment by Nin3s** [comment] 2023-04-11 14:43
this is also after creating a new account

**Comment by Victoria-Williamson** [comment] 2023-04-11 16:16
Closing because this is confirmed to be linked to the other issue

**Closed by Victoria-Williamson** 2023-04-11 16:16 UTC
Labels: bug
